## Rules

### Hierarchy

- Models have three levels of complexity: easy, middle, hard.
   - The corresponding cost also have three levels: cheap, medium, expensive
   - In each level, the accuracy is uniformly distributed. The more the cost, the higher the accuracy
   - The relation between accuracy is: [C/avg(C) * 0.9 , C/avg(C) * 0.98] in each level

### Mapping

- Divide the models into two groups: cheap + medium; medium + expensive
- Divide the tasks into two groups as well
- Divide the models into smaller cluster: #model/3 (C+M); #model/5 (M+E)
- For each model in the small cluster, randomly assign up to 3 (C+M) / 5 (M+E) tasks.

### Selectivity & Cost

- Related to Task, assign to each task randomly
- Related to Model, assign three levels of cost randomly

In [117]:
M = 100
N = 40
num_of_model = M
num_of_task = N

### Cost

In [118]:
import numpy as np
c1 = np.random.uniform(5,10,M//3)
c2 = np.sort(np.random.uniform(15,30,M//3))
c3 = np.random.uniform(40,60,M-(M//3)-(M//3))
c3

array([45.17831236, 56.6648742 , 47.7438239 , 49.76110426, 58.32268248,
       53.43867654, 54.02909846, 55.70625408, 45.68004382, 49.0602708 ,
       50.61061689, 52.6950475 , 56.88090088, 59.7917546 , 40.53143323,
       50.51627452, 46.18873121, 44.2246767 , 46.43517799, 50.67039286,
       52.39553081, 47.59916806, 57.13792076, 49.24537302, 49.35709192,
       56.21395764, 59.78037104, 48.45597992, 48.8735755 , 56.90844844,
       46.14463763, 50.44931839, 54.14401675, 40.42383536])

### Selectivity

In [119]:
s = np.random.uniform(0.3,0.9,N)

### Mapping

In [120]:
g1 = c1.tolist() + c2.tolist()[:len(c1)//2]
g2 = c2.tolist()[len(c1)//2:] + c3.tolist()
print(len(g1),len(g2))

49 51

In [131]:
import random
import statistics

# g1 is devided into #model//3 clusters [a,b,c],[d,e,f]
# g2 is devided into #model//5 clusters [m,n,o],[x,y,z]
def mapping(cluster,task_range,lower=0,size=3):
    # average cost
    max_cost = max(cluster)
    for idx,item in enumerate(cluster):
        model_task_dict[str(idx+lower)]={}
        count = min(random.randint(1,size),len(task_range))
        random_accu = np.random.uniform(0.93*cluster[idx]/max_cost,0.98*cluster[idx]/max_cost,count)
        random_task = np.random.randint(task_range[0],task_range[-1]+1,count)
        model_task_dict[str(idx+lower)] = {str(random_task[i]):random_accu[i] for i in range(count)}
#     return model_task_dict

def split(a, n):
    k, m = divmod(len(a), n)
    return (a[i * k + min(i, m):(i + 1) * k + min(i + 1, m)] for i in range(n))

In [132]:
model_task_dict = {}
l = [g1,g2]
count = 0
for i in range(2):
    size = 4
    if i==0: 
        task_idx = 0
        task_end = N//2
    else: 
        
        task_idx = N//2
        task_end = N
    task_range = range(task_idx, task_end)
    print(task_range)
    task_range_sub = list(split(task_range, size))
    print(task_range_sub)
    model_range_sub = list(split(l[i],size))
    for j in range(size):
        print((j+1)*(len(task_range)//size))
        mapping(model_range_sub[j],task_range_sub[j],count,size)
        count += len(model_range_sub[j])

range(0, 20)
[range(0, 5), range(5, 10), range(10, 15), range(15, 20)]
5
10
15
20
range(20, 40)
[range(20, 25), range(25, 30), range(30, 35), range(35, 40)]
5
10
15
20

In [133]:
model_task_dict

{'0': {'1': 0.8219084240197865},
 '1': {'4': 0.574001209706049},
 '2': {'3': 0.9264150373509622},
 '3': {'0': 0.6122621302398744, '3': 0.6079324289834667},
 '4': {'2': 0.7372862379262736, '4': 0.7397317989166851},
 '5': {'4': 0.9009935277961709,
  '2': 0.8857062553815764,
  '3': 0.8687414472872008},
 '6': {'3': 0.8702386848380604, '2': 0.830764726520044},
 '7': {'0': 0.58653684273254},
 '8': {'2': 0.9373450187965956,
  '4': 0.9771815889168156,
  '0': 0.9470996663218467},
 '9': {'0': 0.8440919988442565,
  '3': 0.8307999693645663,
  '2': 0.8239880041094723,
  '4': 0.8182963075921207},
 '10': {'0': 0.5674526011265874, '2': 0.5561740559712278},
 '11': {'0': 0.7399386766867744,
  '1': 0.7388285039024215,
  '2': 0.7360559024775157},
 '12': {'2': 0.7889176068739172},
 '13': {'6': 0.5633127938710234, '5': 0.5633554094542121},
 '14': {'6': 0.9530163841462732},
 '15': {'6': 0.8152564173454192},
 '16': {'9': 0.7932234892120443, '7': 0.8059802627649976},
 '17': {'7': 0.6776391455347142},
 '18': {'5': 0.8866788558393695, '7': 0.9074759142076656},
 '19': {'8': 0.6993829104560602},
 '20': {'8': 0.7459407868565309,
  '9': 0.7308793906154093,
  '5': 0.7219636775820625},
 '21': {'5': 0.7965036378810829},
 '22': {'9': 0.7944447704477612,
  '6': 0.7980132442018764,
  '5': 0.781086532969581},
 '23': {'5': 0.5929346829394831,
  '9': 0.5894768535300564,
  '8': 0.585398646557675},
 '24': {'5': 0.822437051311441, '9': 0.806025482868761},
 '25': {'13': 0.5497100267539309,
  '10': 0.5642341794991369,
  '14': 0.5499734819964089},
 '26': {'14': 0.43024240255608825, '13': 0.43567052038175363},
 '27': {'11': 0.3347751391946702,
  '14': 0.3364867046604186,
  '10': 0.3298325842875377},
 '28': {'11': 0.3281589023107597},
 '29': {'11': 0.4973578594364914, '10': 0.5013469471662715},
 '30': {'14': 0.38868686391171564, '11': 0.39255106360074304},
 '31': {'11': 0.3493996724013536},
 '32': {'11': 0.3093266778925769,
  '10': 0.30787969813106564,
  '14': 0.3151376699092024,
  '12': 0.31115329899457883},
 '33': {'11': 0.8397586918023434,
  '12': 0.8701876800334034,
  '14': 0.848189600501604},
 '34': {'12': 0.8601245041251203,
  '11': 0.8854507514222786,
  '13': 0.8781690715142241},
 '35': {'14': 0.9102092616876863},
 '36': {'13': 0.9352159668001638,
  '12': 0.9538214988221514,
  '14': 0.9751024203825991},
 '37': {'19': 0.723185667480564, '16': 0.7301545023615673},
 '38': {'15': 0.7672656136588645},
 '39': {'16': 0.7635402217711638,
  '17': 0.7591439651993626,
  '18': 0.776378043735233},
 '40': {'16': 0.8183083059240153},
 '41': {'17': 0.8210214680062494, '18': 0.837941070378048},
 '42': {'18': 0.8280934175537265},
 '43': {'19': 0.8262021999110758,
  '15': 0.8168671124622711,
  '17': 0.8141967670466962},
 '44': {'17': 0.868826428049048},
 '45': {'19': 0.8867147556268663},
 '46': {'16': 0.874579622654405, '15': 0.8787710048931635},
 '47': {'15': 0.901920701048222, '17': 0.9160051716937885},
 '48': {'16': 0.9390370613961629,
  '18': 0.9693077935870388,
  '15': 0.9572523004109518,
  '17': 0.9385968545741605},
 '49': {'23': 0.7824535436259614, '24': 0.7662830433458787},
 '50': {'20': 0.797708404196594},
 '51': {'23': 0.8474894347199898},
 '52': {'23': 0.8305368558615427,
  '20': 0.8275041693780169,
  '24': 0.8665487183628255},
 '53': {'20': 0.8366413218446354, '24': 0.8442755074539077},
 '54': {'21': 0.8488407850884522, '20': 0.8495707597247775},
 '55': {'24': 0.9156894282374546,
  '20': 0.8823500877525916,
  '22': 0.8907349727605851},
 '56': {'20': 0.9194919941612789,
  '24': 0.8923964210304209,
  '23': 0.8836310897191062},
 '57': {'23': 0.8993887093779396, '22': 0.9089812162774564},
 '58': {'21': 0.9257276729921352},
 '59': {'23': 0.9395943816949621},
 '60': {'22': 0.9480631798600645,
  '20': 0.9375456587841633,
  '21': 0.9246628628512883,
  '24': 0.92619191546907},
 '61': {'20': 0.9733843753692784,
  '21': 0.9601619455865297,
  '23': 0.9566379415505164},
 '62': {'26': 0.4468289026338768},
 '63': {'27': 0.4516022455703451},
 '64': {'26': 0.4513978577668889,
  '27': 0.4570921211153511,
  '25': 0.44764538240734675},
 '65': {'25': 0.46441971059382503,
  '26': 0.4563607818668248,
  '27': 0.4601917667167122},
 '66': {'25': 0.7498584422647632, '29': 0.7581622091178726},
 '67': {'25': 0.9263930908592513, '26': 0.9400489844370541},
 '68': {'26': 0.7740804585511057},
 '69': {'27': 0.8111664309416544, '25': 0.8273421730071664},
 '70': {'28': 0.9381099208960868, '26': 0.9796217599477387},
 '71': {'27': 0.8624883359842811},
 '72': {'27': 0.8938116151369259, '25': 0.9003025791492545},
 '73': {'25': 0.9199462259341241},
 '74': {'26': 0.7475736239221612},
 '75': {'33': 0.7681823654735327, '30': 0.7973368633792703},
 '76': {'33': 0.8159685565336429},
 '77': {'31': 0.8540431267741136},
 '78': {'33': 0.8973906619948498},
 '79': {'32': 0.9310567571975241},
 '80': {'33': 0.6406535647526722, '32': 0.6598869225556403},
 '81': {'33': 0.8161262916439443},
 '82': {'32': 0.7454308050429552, '34': 0.7542966531753659},
 '83': {'30': 0.6932011768940302,
  '32': 0.7053830444966722,
  '33': 0.7018944769915886,
  '34': 0.6976267199735612},
 '84': {'34': 0.7509041341801868, '31': 0.7430964536680111},
 '85': {'34': 0.8097266198017223,
  '30': 0.8116748211123324,
  '31': 0.8069923907456555},
 '86': {'33': 0.8536176879663189},
 '87': {'33': 0.7563673044077744, '30': 0.759244524424134},
 '88': {'35': 0.9021723938421983, '36': 0.890121178382037},
 '89': {'36': 0.7746500032135992, '37': 0.775339894278673},
 '90': {'37': 0.7915854330814107,
  '36': 0.7725584342016828,
  '39': 0.8055051012340684,
  '35': 0.778601446888226},
 '91': {'39': 0.9126855609750677},
 '92': {'37': 0.9339953769100987},
 '93': {'36': 0.7672269454507821,
  '35': 0.7788572860435345,
  '38': 0.7625816003090726},
 '94': {'37': 0.7819759159486479, '39': 0.7665194002556023},
 '95': {'35': 0.9050691012432818, '36': 0.8938812618931854},
 '96': {'36': 0.7193070791192349,
  '39': 0.7280663539742831,
  '35': 0.7429684186750394},
 '97': {'37': 0.7893938097899897},
 '98': {'39': 0.8478111750738934},
 '99': {'35': 0.6528912019937597}}

## Get table from dict

In [134]:
import pandas as pd
df = pd.DataFrame.from_dict(model_task_dict, orient='index')

In [135]:
df

,1,4,3,0,2,6,5,9,7,8,...,33,30,31,32,34,35,36,37,39,38
0,0.821908,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.738829,NaN,NaN,0.739939,0.736056,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,0.574001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,0.739732,NaN,NaN,0.737286,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,0.900994,0.868741,NaN,0.885706,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.933995,NaN,NaN
94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.781976,0.766519,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.789394,NaN,NaN
91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.912686,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.847811,NaN