In [1]:
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon
from pandas.plotting import andrews_curves
import pylab
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [4]:
path = 'yolov3/data/valid.txt'
with open(path_val,'r') as f:
    val_paths = f.readlines()

In [6]:
df_train = pd.read_csv('/Volumes/backup/Data/COCO/annotations/train2017.csv',index_col=0)
df_train

,airplane,apple,backpack,banana,baseball_bat,baseball_glove,bear,bed,bench,bicycle,...,toilet,toothbrush,traffic_light,train,truck,tv,umbrella,vase,wine_glass,zebra
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118284,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
classes = ['toothbrush','handbag','book','vase','toaster','scissors']
for c in classes:
    data = df_train[c].dropna()
    print(len(data))

1007
6841
5332
3593
217
947
12774

In [9]:
{'airplane': 0.86, 'elephant': 0.88, 'clock': 0.74, 'cell phone': 0.57, 'dining table': 0.43, 'cup': 0.64, 'wine glass': 0.62, 'carrot': 0.51, 'bed': 0.61, 'frisbee': 0.77, 'surfboard': 0.74, 'dog': 0.7, 'bottle': 0.6, 'remote': 0.58, 'giraffe': 0.84, 'refrigerator': 0.67, 'person': 0.78, 'laptop': 0.76, 'handbag': 0.38, 'train': 0.79, 'cost': 106}

{'airplane': 0.86,
 'elephant': 0.88,
 'clock': 0.74,
 'cell phone': 0.57,
 'dining table': 0.43,
 'cup': 0.64,
 'wine glass': 0.62,
 'carrot': 0.51,
 'bed': 0.61,
 'frisbee': 0.77,
 'surfboard': 0.74,
 'dog': 0.7,
 'bottle': 0.6,
 'remote': 0.58,
 'giraffe': 0.84,
 'refrigerator': 0.67,
 'person': 0.78,
 'laptop': 0.76,
 'handbag': 0.38,
 'train': 0.79,
 'cost': 106}